
spring:

  #for test - should remove---
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  #for test - should remove---

  profiles.active: local
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://13.125.214.115:3306/tify?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    #username: rising88
    #password: Tify123!
    url: jdbc:mysql://localhost:3306/tify?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          client-id: '417043208647-4staa1cqmcp9bph79l9tv7jusva0tmia.apps.googleusercontent.com'
          client-secret: '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'
          scope:
            - email
            - profile
        kakao:
          client-id: "097d883a03c0da953d919d990701da5f"
          redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope:
            - profile_nickname
            - profile_image
            - account_email
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id

# cors
#cors:
#  allowed-origins: 'http://localhost:3000'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600
#
## jwt secret key
#jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'
#
## secret Key  RedirectUri
#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:8080/auth/token